anc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("create_hierarchy.urls", namespace="blog")),
    path("accounts/", include("django.contrib.auth.urls")),
]

create_hierarchy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import index, generate_db, EmployeeListViews, EmployeeUpdateViews, EmployeeDeleteViews

app_name = "create_hierarchy"

urlpatterns = [
    path("", index, name="index"),
    path("generate_db/", generate_db, name="generate_db"),
    path("employee/<int:pk>/update", EmployeeUpdateViews.as_view(), name="employee_update"),
    path("employee/<int:pk>/delete", EmployeeDeleteViews.as_view(), name="employee_delete"),
    path("employee_list/", EmployeeListViews.as_view(), name="employee_list"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

create_hierarchy/models.py
from django.db import models
from django.urls import reverse


class Employee(models.Model):
    class PositionChoices(models.TextChoices):
        GOD = "god"
        SEO = "seo"
        LEAD = "lead"
        SENIOR = "senior"
        MIDDLE = "middle"
        JUNIOR = "junior"
        TRAINEE = "trainee"

    name = models.CharField(max_length=255)
    position = models.CharField(max_length=255, choices=PositionChoices.choices)
    hire_date = models.DateField()
    email = models.EmailField()
    manager = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    def __str__(self):
        return self.name

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

create_hierarchy/forms.py
from django import forms

from create_hierarchy.models import Employee


class EmployeeForm(forms.ModelForm):

    class Meta:
        model = Employee
        fields = "__all__"


class EmployeeSearchForm(forms.Form):
    search = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search"})
    )

create_hierarchy/views.py
import json
import random

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django_seed import Seed

from create_hierarchy.forms import EmployeeForm, EmployeeSearchForm
from create_hierarchy.models import Employee

POSITION = [
    "god",
    "seo",
    "lead",
    "senior",
    "middle",
    "junior",
    "trainee",
]


def delete_db_and_create_god():
    Employee.objects.all().delete()
    god = Employee(name='GOD', position='god', hire_date='2022-01-01', email='johndoe@example.com')
    god.save()


def generate_json():
    got = Employee.objects.filter(manager=None).first()

    def create_json(employee):
        data = {
            "name": employee.name,
            "position": employee.position,
        }
        children = []
        for child in employee.children.all():
            children.append(create_json(child))
        if children:
            data["children"] = children
        return data

    tree_data = create_json(got)
    with open('static/treedata.json', 'w') as outfile:
        json.dump(tree_data, outfile)


@login_required
def generate_db(request):
    delete_db_and_create_god()

    range_ = 50
    for ind, pos in enumerate(POSITION):
        if ind != 0:
            range_ *= 3
            emp = Employee.objects.filter(position=POSITION[ind - 1])

            seeder = Seed.seeder()
            seeder.add_entity(Employee, range_, {
                "name": lambda x: seeder.faker.first_name(),
                "position": pos,
                "manager": lambda x: random.choice(emp)
            })
            inserted_pks = seeder.execute()

    generate_json()

    return render(request, 'wait.html')


def index(request):
    return render(request, 'index.html')


class EmployeeListViews(generic.ListView):
    model = Employee
    queryset = Employee.objects.all()
    fields = "__all__"
    paginate_by = 50
    ordering = ["id", "position", "name", "hire_date", "email", "manager"]

    def get_queryset(self):
        queryset = super().get_queryset()
        order_by = self.request.GET.get("order_by")
        if order_by in self.ordering:
            return queryset.order_by(order_by)

        search = self.request.GET.get("search", "")

        if search:
            search_filters = Q()
            for field in self.model._meta.fields:
                if hasattr(field, "name"):
                    if field.is_relation:
                        search_filters |= Q(
                            **{f"{field.name}__{field.related_model._meta.pk.name}__iexact": search})
                    else:
                        search_filters |= Q(**{f"{field.name}__iexact": search})
            queryset = queryset.filter(search_filters)

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(EmployeeListViews, self).get_context_data(**kwargs)

        search = self.request.GET.get(
            "search", ""
        )
        context["search_form"] = EmployeeSearchForm(
            initial={
                "search": search
            }
        )

        return context


class EmployeeUpdateViews(LoginRequiredMixin, generic.UpdateView):
    model = Employee
    form_class = EmployeeForm
    success_url = reverse_lazy("create_hierarchy:employee_list")


class EmployeeDeleteViews(LoginRequiredMixin, generic.DeleteView):
    model = Employee
    success_url = reverse_lazy("create_hierarchy:employee_list")

user/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ANC</title>
  <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
{% load static %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="buttonGroup">
        <h3>
          <a class="button" href="{% url 'create_hierarchy:index' %}">Hierarchy of Employee </a>|
          <a class="button" href="{% url 'create_hierarchy:employee_list' %}">List of Employee (detail) </a>|
          <a class="button" href="{% url 'create_hierarchy:generate_db' %}">Generate fake Employees </a>|
          {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">Logout</a>
          {% else %}
            <a href="{% url 'login' %}">Login</a>

  {% endif %}
        </h3>
    </div>
{% block content %}{% endblock %}
</body>
</html>

templates/create_hierarchy/employee_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Employee?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/create_hierarchy/employee_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="text_in_crispy_form">{{ object|yesno:"Update,Create" }} Employee</h1>
  <form action="" method="post" novalidate class="text_in_crispy_form">
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/create_hierarchy/employee_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}

  <form action="" method="get" class="form-inline">
  {{ search_form|crispy }}
    <input type="submit" value="🔍">
  </form>

<table class="table">
  <tr>
    <th><a href="?order_by=name">Name</a></th>
    <th><a href="?order_by=position">Position</a></th>
    <th><a href="?order_by=hire_date">Hire date</a></th>
    <th><a href="?order_by=email">Email</a></th>
    <th><a href="?order_by=manager">Manager</a></th>
    <th>Update</th>
    <th>Delete</th>
  </tr>
    {% for employee in employee_list %}
      <tr>
        <td>{{ employee.name }}</td>
        <td>{{ employee.position }}</td>
        <td>{{ employee.hire_date }}</td>
        <td>{{ employee.email }}</td>
        <td>{{ employee.manager }}</td>
        <td><a href="{% url "create_hierarchy:employee_update" pk=employee.id %} ">Update</a></td>
        <td><a href="{% url "create_hierarchy:employee_delete" pk=employee.id %} ">Delete</a></td>
      </tr>
    {% endfor %}
  </table>
  {% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"></li>
      <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}" class="page-link">prev</a>
    {% endif %}

    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>

    {% if page_obj.has_next %}
      <li class="page-item"></li>
      <a href="?page={{ page_obj.next_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}" class="page-link">next</a>
    {% endif %}
  </ul>
{% endif %}
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
    <div id="chart">
    </div>
    {% load static %}
    <script src="{% static 'd3.js'%}"></script>
    <script src="{% static 'd3-selection-multi.js'%}"></script>
    <script type="text/javascript" src="{% static 'treedata.json' %}"></script>
    <script src="{% static 'main.js'%}"></script>
{% endblock %}

templates/wait.html
{% extends "base.html" %}
{% block content %}
<h1>Done! Fake data generated.</h1>
{% endblock %}